version: "3"

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - "5000:5000"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      APP_NAME: LearnMongo
      PORT: 5000
      DB_URI: mongodb://mongo_db:27017/mongolearn
    depends_on:
      - mongo_db
  
volumes:
  mongo_db: {}